config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

class ProxySubdomain
  def self.matches? req
    req.subdomain.present? && req.subdomain != "www"
  end
end
class NoSubdomain
  def self.matches? req
    !req.subdomain.present? || (req.subdomain.present? && req.subdomain == "www")
  end
end
Rails.application.routes.draw do

  devise_for :users, skip: [:registrations]
  devise_scope :user do
    unauthenticated do
      get "/" =>  "devise/sessions#new"
    end
    authenticated :user do
      get '/users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
      put '/users/:id' => 'devise/registrations#update', as: 'registration'
    end
  end

  authenticated :user do
    constraints(ProxySubdomain) do
      mount Journalist::Proxy::Server, at: '/'
    end
  end

  constraints(NoSubdomain) do
    authenticated :user, lambda{|u| u.role == "ADMIN"} do
      mount Sidekiq::Web => "/sidekiq"
      namespace :admin do
        resources :journals, except: :show do
          resources :journal_accounts, except: :show do
            with_options action: "set_status" do |map|
              map.post '/enable', action: "set_status"
              map.post '/disable', action: "set_status"
            end
          end
        end
      end
    end
    root to: "static_page#home"
  end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  include Journalist::JournalModel
end

app/models/journal_account.rb
class JournalAccount < ActiveRecord::Base
  include Journalist::JournalAccountModel
end

app/models/user.rb
class User < ActiveRecord::Base
  ROLE = ["DEFAULT", "ADMIN"]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  validates_presence_of :full_name

  def is_admin?
    self.role == "ADMIN"
  end
end

app/controllers/admin/journal_accounts_controller.rb
class Admin::JournalAccountsController < ApplicationController
  before_action :admin_user!
  before_action :set_journal
  before_action :set_journal_account, only: [:show, :edit, :update, :destroy]

  # GET /admin/journal_accounts
  # GET /admin/journal_accounts.json
  def index
    respond_to do |format|
      format.html
      format.json {render json: JournalAccountDatatables.new(view_context)}
    end
  end

  # GET /admin/journal_accounts/new
  def new
    @journal_account = @journal.journal_accounts.new
    respond_to do |format|
      format.js
    end
  end

  # GET /admin/journal_accounts/1/edit
  def edit
  end

  # POST /admin/journal_accounts
  # POST /admin/journal_accounts.json
  def create
    @journal_account = @journal.journal_accounts.new(journal_account_params)
    respond_to do |format|
      if @journal_account.save
        flash[:notice] = "Journal account was successfully created."
        format.js
      else
        format.js { render :new }
      end
    end
  end

  # PATCH/PUT /admin/journal_accounts/1
  # PATCH/PUT /admin/journal_accounts/1.json
  def update
    respond_to do |format|
      if @journal_account.update(journal_account_params)
        flash[:notice] = "Journal account was successfully updated."
        format.js
      else
        format.js { render :edit }
      end
    end
  end

  # DELETE /admin/journal_accounts/1
  # DELETE /admin/journal_accounts/1.json
  def destroy
    @journal_account.destroy
    respond_to do |format|
      if @journal_account.errors.any?
        format.html { redirect_to admin_journal_journal_accounts_url(@journal), alert: "You can't deleting enabled account" }
      else
        format.html { redirect_to admin_journal_journal_accounts_url(@journal), notice: 'Journal account was successfully destroyed.' }
      end
    end
  end

  def set_status
    @journal_account = @journal.journal_accounts.find(params[:journal_account_id])
    @journal_account.toggle_enable
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal_account
      @journal_account = @journal.journal_accounts.find(params[:id])
    end

    def set_journal
      @journal = Journal.find(params[:journal_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def journal_account_params
      params.require(:journal_account).permit(:username, :password, :other)
    end
end

app/controllers/admin/journals_controller.rb
class Admin::JournalsController < ApplicationController
  before_action :admin_user!
  before_action :set_journal, only: [:show, :edit, :update, :destroy]

  # GET /journals
  # GET /journals.json
  def index
    respond_to do |format|
      format.html
      format.json {render json: JournalDatatables.new(view_context)}
    end
  end

  # GET /journals/new
  def new
    @journal = Journal.new
    respond_to do |format|
      format.js
    end
  end

  # GET /journals/1/edit
  def edit
    respond_to do |format|
      format.js
    end
  end

  # POST /journals
  # POST /journals.json
  def create
    @journal = Journal.new(journal_params)

    respond_to do |format|
      if @journal.save
        flash[:notice] = "Jounal resource was successfully created."
        format.js
      else
        format.js { render :new }
      end
    end
  end

  # PATCH/PUT /journals/1
  # PATCH/PUT /journals/1.json
  def update
    respond_to do |format|
      if @journal.update(journal_params)
        flash[:notice] = "Journal resource was successfuly updated"
        format.js
      else
        format.js { render :edit }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @journal.destroy
    respond_to do |format|
      format.html { redirect_to admin_journals_url, notice: 'Journal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal
      @journal = Journal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def journal_params
      params.require(:journal).permit(:name, :driver)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper
  before_filter :authenticate_user!

  # def after_sign_in_path_for(resource_or_scope)
  #   authenticated_root_path
  # end

  # def after_sign_out_path_for(resource_or_scope)
  #   root_path
  # end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end
end

app/helpers/admin/journal_accounts_helper.rb
module Admin::JournalAccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title text
    return "#{text} | Journalist" if text.present?
    return "Journalist"
  end

  def flash_class level
    css_class = {'notice' => "alert alert-info", 'success' => "alert alert-success", 'error' => "alert alert-danger", 'alert' => "alert alert-danger"}
    css_class[level]
  end

  def flash_icon level
    css_class = {'notice' => "fa fa-rocket", 'success' => "fa fa-check", 'error' => "fa fa-times", 'alert' => "fa fa-times"}
    css_class[level]
  end

  def message_status level
    status = {'notice' => "Notice", 'success' => "Success", 'error' => "Error", 'alert' => "Alert"}
    status[level]
  end

  def is_admin?
    user_signed_in? && current_user.is_admin?
  end

  def admin_user!
    redirect_to(root_path, alert: "You don't have any permission to entering this page") unless is_admin?
  end

end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/admin/journal_accounts/_form.html.haml
#journal-account-modal.modal.fade{tabindex: "-1", role: "dialog", "aria-labelledby" => "journalAccountModalLabel", "aria-hidden" => "true", "data-backdrop" => "static", "data-keyboard" => "true"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type: "button", "data-dismiss" => "modal", "aria-hidden" => "true"} &times;
        %h4#journalAccountModalLabel.modal-title
          = @journal_account.new_record? ? "Add new journal account" : "Edit journal account"
      = form_for [:admin, @journal, @journal_account], remote: true, html: {role: "form", class: "form-horizontal"} do |f|
        .modal-body
          = render "layouts/shared/errors", object: f.object
          .form-group
            = f.label :username, "Username", class: "col-sm-3 control-label"
            .col-sm-9
              = f.text_field :username, class: "form-control", placeholder: "Journal resource username"
          .form-group
            = f.label :password, "Password", class: "col-sm-3 control-label"
            .col-sm-9
              = f.text_field :password, class: "form-control", placeholder: "Journal resource password"
          .form-group
            = f.label :other, "Other", class: "col-sm-3 control-label"
            .col-sm-9
              = f.text_field :other, class: "form-control", placeholder: "Journal resource other security key"
          .modal-footer
            %button.btn.btn-primary{type: "submit"}
              %i.fa.fa-upload
              Save
            %button.btn.btn-default{type: "button", "data-dismiss" => "modal"}
              %i.fa.fa-times
              Cancel

app/views/admin/journal_accounts/create.js.erb
<% content_for :additional_js do %>
  var a = $("#journal-account-tables").dataTable();
  a._fnAjaxUpdate();
<%end%>
<%= render partial: "layouts/shared/javascripts/responder", locals: { selector: "#journal-account-modal"} %>

app/views/admin/journal_accounts/edit.js.erb
<% html = j render('form') %>
<%= render partial: "layouts/shared/javascripts/show_modal", locals: {template: html, selector: "#journal-account-modal"} %>

app/views/admin/journal_accounts/index.html.haml
- provide(:title, "Manage Journal Account")
#journal-accounts
  %header
    .col-md-12
      .row
        .col-md-6
          %h2 Manage journal account
        .col-md-6
          .action{style: "margin-top: 20px;"}
            .pull-right
              = link_to new_admin_journal_journal_account_path(@journal), class: "btn btn-primary btn-lg", remote: true do
                %i.fa.fa-key
                Add Journal Account
    .clearfix
  %hr
  %section
    %table#journal-account-tables.table.table-bordered{"data-url" => admin_journal_journal_accounts_path(format: "json")}
      %thead
        %tr
          %th
            .text-center Username
          %th
            .text-center Password
          %th
            .text-center Other
          %th
            .text-center Enabled
          %th
            .text-center Action
      %tbody

app/views/admin/journal_accounts/new.js.erb
<% html = j render('form') %>
<%= render partial: "layouts/shared/javascripts/show_modal", locals: {template: html, selector: "#journal-account-modal"} %>

app/views/admin/journal_accounts/set_status.js.erb
var a = $("#journal-account-tables").dataTable();
a._fnAjaxUpdate();

app/views/admin/journal_accounts/update.js.erb
<% content_for :additional_js do %>
  var a = $("#journal-account-tables").dataTable();
  a._fnAjaxUpdate();
<%end%>
<%= render partial: "layouts/shared/javascripts/responder", locals: { selector: "#journal-account-modal"} %>

app/views/admin/journals/_form.html.haml
#journal-modal.modal.fade{tabindex: "-1", role: "dialog", "aria-labelledby" => "journalModalLabel", "aria-hidden" => "true", "data-backdrop" => "static", "data-keyboard" => "true"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type: "button", "data-dismiss" => "modal", "aria-hidden" => "true"} &times;
        %h4#journalModalLabel.modal-title
          = @journal.new_record? ? "Create new journal resource" : "Edit journal resources"
      = form_for [:admin, @journal], remote: true, html: {role: "form", class: "form-horizontal"} do |f|
        .modal-body
          = render "layouts/shared/errors", object: f.object
          .form-group
            = f.label :name, "Name", class: "col-sm-3 control-label"
            .col-sm-9
              = f.text_field :name, class: "form-control", placeholder: "Journal resources name"
          .form-group
            = f.label :driver, "Driver", class: "col-sm-3 control-label"
            .col-sm-9
              = f.select :driver, options_for_select(Journal::DRIVER, selected: @journal.driver), {}, {class: "form-control"}
          .modal-footer
            %button.btn.btn-primary{type: "submit"}
              %i.fa.fa-upload
              Save
            %button.btn.btn-default{type: "button", "data-dismiss" => "modal"}
              %i.fa.fa-times
              Cancel

app/views/admin/journals/create.js.erb
<% content_for :additional_js do %>
  var a = $("#journal-tables").dataTable();
  a._fnAjaxUpdate();
<%end%>
<%= render partial: "layouts/shared/javascripts/responder", locals: { selector: "#journal-modal"} %>

app/views/admin/journals/edit.js.erb
<% html = j render('form') %>
<%= render partial: "layouts/shared/javascripts/show_modal", locals: {template: html, selector: "#journal-modal"} %>

app/views/admin/journals/index.html.haml
- provide(:title, "Manage journal")
#journals
  %header
    .col-md-12
      .row
        .col-md-6
          %h2 Manage journal
        .col-md-6
          .action{style: "margin-top: 20px;"}
            .pull-right
              =link_to new_admin_journal_path, class: "btn btn-primary btn-lg", remote: true do
                %i.fa.fa-book
                Add Journal
    .clearfix
  %hr
  %section
    %table#journal-tables.table.table-bordered{"data-url" => admin_journals_path(format: "json")}
      %thead
        %tr
          %th
            .text-center Name
          %th
            .text-center Driver
          %th
            .text-center Journal Account
          %th
            .text-center Manage Journal Account
          %th
            .text-center Action

app/views/admin/journals/new.js.erb
<% html = j render('form') %>
<%= render partial: "layouts/shared/javascripts/show_modal", locals: {template: html, selector: "#journal-modal"} %>

app/views/admin/journals/update.js.erb
<% content_for :additional_js do %>
  var a = $("#journal-tables").dataTable();
  a._fnAjaxUpdate();
<%end%>
<%= render partial: "layouts/shared/javascripts/responder", locals: { selector: "#journal-modal"} %>

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{style: "padding-top: 50px;"}
    = render "layouts/shared/menu"
    #flash
      = render partial: "layouts/shared/flash", locals: {flash: flash}
    #wraper.container
      = yield

app/views/layouts/devise.html.haml
%html{:lang => "en"}
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    #flash
      = render partial: "layouts/shared/flash", locals: {flash: flash}
    .container
      = yield

app/views/layouts/shared/_errors.html.haml
- if object.errors.any?
  #error-explenation
    .alert.alert-danger
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
      - object.errors.full_messages.each do |msg|
        %li * #{msg}.
  %hr

app/views/layouts/shared/_flash.html.haml
- flash.each do |key, value|
  %div{class: flash_class(key), style: "display: none;"}
    %button.close &times;
    %span{class: flash_icon(key)}
    %strong= "#{message_status(key)} Message"
    %hr.message-inner-separator
    %p= raw(value)

app/views/layouts/shared/_menu.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Journalist", root_path, class: "navbar-brand"
    .collapse.navbar-collapse
      - if is_admin?
        %ul.nav.navbar-nav
          %li= link_to "User", "#"
          %li= link_to "Journal", admin_journals_path
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            = link_to "#", class: "dropdown-toggle", "data-toggle" => "dropdown" do
              %i.fa.fa-user
              = current_user.full_name
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to edit_user_registration_path do
                  %i.fa.fa-key
                  Edit Password
              %li
                = link_to destroy_user_session_path, method: :delete do
                  %i.fa.fa-power-off
                  Sign out

app/views/layouts/shared/javascripts/_responder.js.erb
<%= yield :additional_js %>
$("<%= selector %>").modal('hide');
$("<%= selector %>").on('hidden.bs.modal', function(e){
  $(e.target).remove();
  $("#flash").append("<%= j render partial: "layouts/shared/flash", locals: {flash: flash}%>");
  $("#flash .alert").each(function(i, e){
    $(this).delay(i*1000).fadeIn('slow');
  });
});

app/views/layouts/shared/javascripts/_show_modal.js.erb
var modal = $("<%= selector %>");
if (modal.length == 1) {
  modal.modal("hide");
  modal.on('hidden.bs.modal', function(e){
    $(e.target).remove();
    $("body").append("<%= template %>");
    $("<%= selector %>").modal({show: true})
    <%= yield :additional_js %>
  });
}else{
  $("body").append("<%= template %>");
  $("<%= selector %>").modal({show: true})
  <%= yield :additional_js %>
}

app/views/static_page/home.html.haml
%h1 Hello World